function [M11_ev,M12_ev,M21_ev,M22_ev]=LFT_ev(n_psi,n_p,Nd)
    M11_ev=zeros(n_p*(2*n_psi+Nd),n_p*(2*n_psi+Nd));
    M12_ev=blkdiag(kron(ones(n_p,1),eye(n_psi)), ...
        kron(ones(n_p,1),eye(n_psi)), ...
        kron(ones(n_p,1),eye(Nd)));
    M21_ev=blkdiag([zeros(n_psi,n_psi*n_p);eye(n_psi*n_p)], ...
        [zeros(n_psi,n_psi*n_p);eye(n_psi*n_p)], ...
        [zeros(Nd,Nd*n_p);eye(Nd*n_p)]);
    M22_ev=blkdiag([eye(n_psi);zeros(n_p*n_psi,n_psi)], ...
        [eye(n_psi);zeros(n_p*n_psi,n_psi)], ...
        [eye(Nd);zeros(n_p*Nd,Nd)]);
end