function [U1,U2,U3,U4]=getUMatirx(p_1,p_2,p_3,p_4,n_x,Nd,n_1)


Upsilon_p1=blkdiag(kron(diag(p_1),eye(n_x)), ...
    kron(diag(p_1),eye(n_x)), ...
    kron(diag(p_1),eye(n_x)), ...
    kron(diag(p_1),eye(n_x)), ...
    kron(diag(p_1),eye(Nd)));
Upsilon_p2=blkdiag(kron(diag(p_2),eye(n_x)), ...
    kron(diag(p_2),eye(n_x)), ...
    kron(diag(p_2),eye(n_x)), ...
    kron(diag(p_2),eye(n_x)), ...
    kron(diag(p_2),eye(Nd)));
Upsilon_p3=blkdiag(kron(diag(p_3),eye(n_x)), ...
    kron(diag(p_3),eye(n_x)), ...
    kron(diag(p_3),eye(n_x)), ...
    kron(diag(p_3),eye(n_x)), ...
    kron(diag(p_3),eye(Nd)));
Upsilon_p4=blkdiag(kron(diag(p_4),eye(n_x)), ...
    kron(diag(p_4),eye(n_x)), ...
    kron(diag(p_4),eye(n_x)), ...
    kron(diag(p_4),eye(n_x)), ...
    kron(diag(p_4),eye(Nd)));

U1=[eye(n_1);Upsilon_p1];
U2=[eye(n_1);Upsilon_p2];
U3=[eye(n_1);Upsilon_p3];
U4=[eye(n_1);Upsilon_p4];
