function [U1,U2]=getUMatirx(p_1,p_2,n_psi,Nd,n_1_hat)


Upsilon_p1=blkdiag(kron(diag(p_1),eye(n_psi)), ...
    kron(diag(p_1),eye(n_psi)), ...
    kron(diag(p_1),eye(n_psi)), ...
    kron(diag(p_1),eye(n_psi)), ...
    kron(diag(p_1),eye(Nd)));
Upsilon_p2=blkdiag(kron(diag(p_2),eye(n_psi)), ...
    kron(diag(p_2),eye(n_psi)), ...
    kron(diag(p_2),eye(n_psi)), ...
    kron(diag(p_2),eye(n_psi)), ...
    kron(diag(p_2),eye(Nd)));

U1=[eye(n_1_hat);Upsilon_p1];
U2=[eye(n_1_hat);Upsilon_p2];

